<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-12-05T08:56:26+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Dubai',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
