<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2022-01-07T14:16:43+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.7',
    'version_db_installed' => '20210623000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1638680185,
        'do_page_reindex_check' => false,
        'latest_version' => '8.5.7',
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => false,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
