<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-12-05T17:40:44+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'IACAPAP 2022',
        ],
    ],
];
